["Library/Developer/Xcode/UserData/FontAndColorThemes/Nord.xccolortheme"]
type = "file"
url = "https://raw.githubusercontent.com/arcticicestudio/nord-xcode/develop/src/Nord.xccolortheme"
refreshPeriod = "168h"
[".config/nvim"]
type = "git-repo"
url = "https://github.com/omgitsads/nvim.git"
refreshPeriod = "168h"
