[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
[".local/share/nvim/site/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
["~/Library/Developer/Xcode/UserData/FontAndColorThemes/Nord.xccolortheme"]
    type = "file"
    url = "https://raw.githubusercontent.com/arcticicestudio/nord-xcode/develop/src/Nord.xccolortheme"
    refreshPeriod = "168h"
